"""
Reports router — generates a PDF weekly status report.
"""

from datetime import date
from io import BytesIO
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from fpdf import FPDF, XPos, YPos
from .. import crud, models
from ..auth import get_current_user
from ..database import get_db

router = APIRouter()

# ── Colour palette ────────────────────────────────────────────────────────────
BRAND   = (99,  102, 241)   # indigo
GREEN   = (34,  197,  94)
AMBER   = (245, 158,  11)
RED     = (239,  68,  68)
BLUE    = (59,  130, 246)
SLATE   = (71,  85, 105)
LIGHT   = (241, 245, 249)
WHITE   = (255, 255, 255)
DARK    = (30,  41,  59)

STATUS_COLOR = {
    "on_track":  GREEN,
    "at_risk":   AMBER,
    "delayed":   RED,
    "completed": BLUE,
    "on_hold":   (148, 163, 184),
}
STATUS_LABEL = {
    "on_track":  "On Track",
    "at_risk":   "At Risk",
    "delayed":   "Delayed",
    "completed": "Completed",
    "on_hold":   "On Hold",
}
PRIORITY_LABEL = {"high": "High", "medium": "Medium", "low": "Low"}


class ProjectReport(FPDF):
    def __init__(self, generated_by: str):
        super().__init__()
        self.generated_by = generated_by
        self.set_auto_page_break(auto=True, margin=18)

    # ── Header ────────────────────────────────────────────────────────────────
    def header(self):
        # Brand bar
        self.set_fill_color(*BRAND)
        self.rect(0, 0, 210, 14, "F")
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 11)
        self.set_xy(10, 3)
        self.cell(0, 8, "ProjectTracker", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(*DARK)
        self.ln(4)

    # ── Footer ────────────────────────────────────────────────────────────────
    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*SLATE)
        self.cell(0, 6, f"Generated by {self.generated_by}  ·  {date.today().strftime('%B %d, %Y')}  ·  Page {self.page_no()}",
                  align="C")


def _section_title(pdf: FPDF, text: str):
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*BRAND)
    pdf.cell(0, 7, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(*BRAND)
    pdf.set_line_width(0.5)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
    pdf.ln(3)
    pdf.set_text_color(*DARK)


def _kpi_box(pdf: FPDF, x: float, y: float, label: str, value: str, color: tuple):
    w, h = 42, 22
    pdf.set_fill_color(*LIGHT)
    pdf.rect(x, y, w, h, "F")
    pdf.set_xy(x, y + 2)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*color)
    pdf.cell(w, 8, value, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_xy(x, y + 12)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*SLATE)
    pdf.cell(w, 5, label, align="C")


def _progress_bar(pdf: FPDF, x: float, y: float, pct: int, w: float = 28):
    h = 3
    pdf.set_fill_color(226, 232, 240)
    pdf.rect(x, y, w, h, "F")
    if pct > 0:
        color = GREEN if pct >= 70 else AMBER if pct >= 40 else RED
        pdf.set_fill_color(*color)
        pdf.rect(x, y, w * pct / 100, h, "F")


def _safe(text: str) -> str:
    """Replace non-latin1 characters so Helvetica doesn't choke."""
    return (text
        .replace("—", "-")   # em dash
        .replace("–", "-")   # en dash
        .replace("…", "...") # ellipsis
        .encode("latin-1", errors="replace")
        .decode("latin-1"))


def _status_badge(pdf: FPDF, x: float, y: float, status: str):
    label = STATUS_LABEL.get(status, status)
    color = STATUS_COLOR.get(status, SLATE)
    pdf.set_font("Helvetica", "B", 7)
    tw = pdf.get_string_width(label) + 6
    # light background
    r, g, b = color
    pdf.set_fill_color(min(r+180,255), min(g+180,255), min(b+180,255))
    pdf.rect(x, y, tw, 5, "F")
    pdf.set_text_color(*color)
    pdf.set_xy(x, y)
    pdf.cell(tw, 5, label, align="C")
    pdf.set_text_color(*DARK)
    return tw


@router.get("/pdf")
def generate_pdf_report(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Generate and stream a PDF weekly status report."""
    projects = crud.get_projects(db, limit=200)
    stats    = crud.get_dashboard_stats(db)
    today    = date.today()

    pdf = ProjectReport(generated_by=current_user.name)
    pdf.add_page()

    # ── Title block ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*DARK)
    pdf.cell(0, 10, "Weekly Project Status Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*SLATE)
    pdf.cell(0, 5, f"Period ending {today.strftime('%B %d, %Y')}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(6)

    # ── KPI boxes ────────────────────────────────────────────────────────────
    _section_title(pdf, "Executive Summary")
    pdf.ln(2)
    kpis = [
        ("Total Projects",  str(stats.total),         BRAND),
        ("On Track",        str(stats.on_track),       GREEN),
        ("At Risk",         str(stats.at_risk),        AMBER),
        ("Delayed",         str(stats.delayed),        RED),
        ("Completed",       str(stats.completed),      BLUE),
        ("Avg Progress",    f"{stats.avg_progress}%",  (99,102,241)),
    ]
    base_y = pdf.get_y()
    for i, (label, value, color) in enumerate(kpis):
        _kpi_box(pdf, 10 + i * 33, base_y, label, value, color)
    pdf.ln(32)

    # ── Critical projects ─────────────────────────────────────────────────────
    critical = [p for p in projects if p.status in ("delayed", "at_risk")]
    if critical:
        _section_title(pdf, f"[!] Critical Projects ({len(critical)})")
        for p in critical:
            color = RED if p.status == "delayed" else AMBER
            pdf.set_fill_color(*[min(c+190,255) for c in color])
            pdf.rect(10, pdf.get_y(), 190, 12, "F")
            # Status badge
            _status_badge(pdf, 12, pdf.get_y() + 3.5, p.status)
            # Name
            pdf.set_xy(48, pdf.get_y() + 2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*DARK)
            name = p.name[:50] + ("..." if len(p.name) > 50 else "")
            pdf.cell(90, 5, _safe(name))
            # Owner
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*SLATE)
            owner = p.owner.name if p.owner else "-"
            pdf.cell(40, 5, owner)
            # Due date
            due = p.end_date.strftime("%b %d, %Y") if p.end_date else "-"
            pdf.set_text_color(*color)
            pdf.cell(30, 5, due, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(2)
        pdf.ln(4)

    # ── All projects table ────────────────────────────────────────────────────
    _section_title(pdf, "All Projects")

    # Table header
    headers = ["Project", "Area", "Status", "Progress", "Priority", "Owner", "Due Date"]
    widths  = [55, 28, 24, 32, 18, 25, 22]
    pdf.set_fill_color(*BRAND)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 7)
    for h, w in zip(headers, widths):
        pdf.cell(w, 6, h, fill=True)
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", "", 7.5)
    for i, p in enumerate(projects):
        row_y = pdf.get_y()
        fill  = i % 2 == 0
        if fill:
            pdf.set_fill_color(*LIGHT)
            pdf.rect(10, row_y, 190, 10, "F")

        pdf.set_text_color(*DARK)
        pdf.set_xy(10, row_y + 2)

        # Name
        name = p.name[:30] + ("..." if len(p.name) > 30 else "")
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.cell(widths[0], 6, _safe(name))

        # Area
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*SLATE)
        pdf.cell(widths[1], 6, _safe((p.area or "-")[:14]))

        # Status badge
        badge_x = pdf.get_x()
        badge_y = row_y + 2.5
        _status_badge(pdf, badge_x, badge_y, p.status)
        pdf.set_xy(badge_x + widths[2], row_y + 2)

        # Progress bar + %
        prog_x = pdf.get_x()
        _progress_bar(pdf, prog_x, row_y + 4, p.progress, 18)
        pdf.set_xy(prog_x + 20, row_y + 2)
        color = GREEN if p.progress >= 70 else AMBER if p.progress >= 40 else RED
        pdf.set_text_color(*color)
        pdf.set_font("Helvetica", "B", 7)
        pdf.cell(10, 6, f"{p.progress}%")

        # Priority
        pdf.set_xy(10 + sum(widths[:4]), row_y + 2)
        prio_color = RED if p.priority == "high" else AMBER if p.priority == "medium" else GREEN
        pdf.set_text_color(*prio_color)
        pdf.set_font("Helvetica", "B", 7)
        pdf.cell(widths[4], 6, PRIORITY_LABEL.get(p.priority, p.priority))

        # Owner
        pdf.set_xy(10 + sum(widths[:5]), row_y + 2)
        pdf.set_text_color(*SLATE)
        pdf.set_font("Helvetica", "", 7.5)
        owner = (p.owner.name.split()[0] if p.owner else "-")[:12]
        pdf.cell(widths[5], 6, owner)

        # Due date
        pdf.set_xy(10 + sum(widths[:6]), row_y + 2)
        due_str = p.end_date.strftime("%b %d, %Y") if p.end_date else "-"
        if p.end_date and p.end_date < today:
            pdf.set_text_color(*RED)
        else:
            pdf.set_text_color(*SLATE)
        pdf.cell(widths[6], 6, due_str)

        pdf.ln(10)

   